config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, 
    length: { minimum: 1, maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index

        @posts = Post.all
    end
  
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if params[:back]
            render :new
        else 
            if @post.save
                redirect_to new_post_path
            else
                render :new
            end
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def show
        @post = Post.find(params[:id])
        redirect_to posts_path
      end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to post_path, notice: "Your meow edited!"
        else
            render :edit
        end
    end

    def destroy
       @post = Post.find(params[:id]) 
       @post.destroy
       redirect_to posts_path, notice:"Your meow deleted!"
    end

    def confirm
        @post = Post.new(post_params)
        render :new if @post.invalid?
    end

    private
    
    def post_params
        params.require(:post).permit(:content)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "page">
      <%= image_tag 'cat_mike.png' %>
      
        <%= yield %>

      <footer>Meow like a cat!</footer>
    </div>
  </body>
</html>

app/views/posts/confirm.html.erb
<h3>Confirm your meow!</h3>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= @post.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

 <%= form.hidden_field :content %>
  <p>meow:<%= @post.content %></p>
  <%= form.submit  "meow!" %>
  <%= form.submit "back!", name: 'back' %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit your meow!</h2>
<%= form_with(model: @post, local: true) do |form| %>
    <div class="post_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit %>
  <% end %>

app/views/posts/index.html.erb
<h1>Your meows</h1>
<table>
  <tr>
    <th>meow!</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.content %></td>
      <td><%= link_to 'Edit your meow!', edit_post_path(post.id) %></td>
      <td><%= link_to 'Delete your meow!', post_path(post.id), method: :delete %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New meow!', new_post_path %>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true, url: confirm_posts_path) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    
    <div class="post_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit %>
<% end %>
  <%= link_to "check your meows!", posts_path %>